export const dynamic = 'force-dynamic';

import { createChildRegisterRoutes } from '@/lib/api/route-factory';
import type { EngineeringEstimate } from '@/types/engineering-estimate';
import { createEngineeringEstimateRequestSchema } from '@/types/engineering-estimate.schema';

/**
 * GET/POST /api/engineering-estimates/[packageId] — ราคากลาง records per
 * procurement package (PR-24). Creation runs inside one transactional
 * audit, matching the hand-written handler.
 *
 * PR-35 — generated by the route factory.
 */
export const { GET, POST } = createChildRegisterRoutes<
  EngineeringEstimate,
  typeof createEngineeringEstimateRequestSchema._output,
  { projectId: string }
>({
  paramName: 'packageId',
  resolveParent: (repos, packageId) => repos.procurementPackages.findById(packageId),
  notFoundMessage: (packageId) => `Procurement package ${packageId} not found`,
  createSchema: createEngineeringEstimateRequestSchema,
  transactionalCreate: true,
  list: (repos, packageId) =>
    repos.engineeringEstimates.listByProcurementPackage(packageId),
  create: (repos, entity) => repos.engineeringEstimates.create(entity),
  build: (body, { parentId }) => ({
    id: `est-${crypto.randomUUID()}`,
    procurementPackageId: parentId,
    boqId: body.boqId ?? null,
    basis: body.basis,
    estimatedTotal: body.estimatedTotal,
    contingencyPercent: body.contingencyPercent,
    estimatedBy: body.estimatedBy.trim(),
    estimatedAt: body.estimatedAt,
    notes: body.notes?.trim() ?? '',
  }),
  audit: {
    action: 'edit_engineering_estimate',
    resourceType: 'engineering_estimate',
    decisionReason: (created) =>
      `record estimate (${created.basis}, ${created.estimatedTotal} THB)`,
  },
});
