export const dynamic = 'force-dynamic';

import { createChildRegisterRoutes } from '@/lib/api/route-factory';
import type { AsBuiltDrawing } from '@/types/as-built-drawing';
import { createAsBuiltDrawingRequestSchema } from '@/types/as-built-drawing.schema';

/**
 * GET/POST /api/as-built-drawings/[packetId] — as-built drawings
 * register per handover packet (PR-26). Creation runs inside one
 * transactional audit.
 *
 * PR-35 — generated by the route factory.
 */
export const { GET, POST } = createChildRegisterRoutes<
  AsBuiltDrawing,
  typeof createAsBuiltDrawingRequestSchema._output,
  { projectId: string }
>({
  paramName: 'packetId',
  resolveParent: (repos, packetId) => repos.handoverPackets.findById(packetId),
  notFoundMessage: (packetId) => `Handover packet ${packetId} not found`,
  createSchema: createAsBuiltDrawingRequestSchema,
  transactionalCreate: true,
  list: (repos, packetId) => repos.asBuiltDrawings.listByHandoverPacket(packetId),
  create: (repos, entity) => repos.asBuiltDrawings.create(entity),
  build: (body, { parentId }) => ({
    id: `ab-${crypto.randomUUID()}`,
    handoverPacketId: parentId,
    drawingNumber: body.drawingNumber.trim(),
    title: body.title.trim(),
    documentFileId: body.documentFileId ?? null,
    revision: body.revision.trim(),
    uploadedAt: new Date().toISOString(),
    notes: body.notes?.trim() ?? '',
  }),
  audit: {
    action: 'create_as_built_drawing',
    resourceType: 'as_built_drawing',
    decisionReason: (created) =>
      `register drawing ${created.drawingNumber} (${created.revision})`,
  },
});
