export const dynamic = 'force-dynamic';

import { createByProjectRegisterRoutes } from '@/lib/api/route-factory';
import type { VendorSow } from '@/types/vendor-sow';
import { createVendorSowRequestSchema } from '@/types/vendor-sow.schema';

/**
 * GET/POST /api/vendor-sows/by-project/[projectId] — DT6 vendor SOWs
 * (PR-30a). 422 IT_ONLY_FEATURE on non-IT projects, before any write.
 *
 * PR-35 — generated by the route factory.
 */
export const { GET, POST } = createByProjectRegisterRoutes<
  VendorSow,
  typeof createVendorSowRequestSchema._output
>({
  requireIt: true,
  createSchema: createVendorSowRequestSchema,
  list: (repos, projectId) => repos.vendorSows.listByProject(projectId),
  create: (repos, entity) => repos.vendorSows.create(entity),
  build: (body, { projectId }) => ({
    id: `sow-${crypto.randomUUID()}`,
    projectId,
    contractId: body.contractId ?? null,
    phase: body.phase.trim(),
    scopeSummary: body.scopeSummary.trim(),
    uatCriteria: body.uatCriteria.trim(),
    warrantyMonths: body.warrantyMonths ?? null,
    state: body.state ?? 'draft',
    signedAt: null,
    acceptedAt: null,
    notes: body.notes?.trim() ?? '',
  }),
  audit: {
    action: 'create_vendor_sow',
    resourceType: 'vendor_sow',
    decisionReason: (created) =>
      `register SOW "${created.phase}" (${created.state})`,
  },
});
