export const dynamic = 'force-dynamic';

import { createByProjectRegisterRoutes } from '@/lib/api/route-factory';
import type { ProcurementPackage } from '@/types/procurement-package';
import { createProcurementPackageRequestSchema } from '@/types/procurement-package.schema';

/**
 * GET/POST /api/procurement-packages/by-project/[projectId] (PR-24).
 *
 * Reads: any role with project visibility. Writes: `edit_basic`.
 * PR-35 — generated by the route factory; the pipeline and envelopes
 * are unchanged from the hand-written handler.
 */
export const { GET, POST } = createByProjectRegisterRoutes<
  ProcurementPackage,
  typeof createProcurementPackageRequestSchema._output
>({
  createSchema: createProcurementPackageRequestSchema,
  list: (repos, projectId) => repos.procurementPackages.listByProject(projectId),
  create: (repos, entity) => repos.procurementPackages.create(entity),
  build: (body, { projectId }) => ({
    id: `pkg-${crypto.randomUUID()}`,
    projectId,
    name: body.name.trim(),
    state: body.state ?? 'draft',
    budgetCeiling: body.budgetCeiling,
    procurementMethod: body.procurementMethod,
    openedAt: body.openedAt ?? null,
    closedAt: body.closedAt ?? null,
    notes: body.notes?.trim() ?? '',
  }),
  audit: {
    action: 'edit_procurement_package',
    resourceType: 'procurement_package',
    decisionReason: (created) =>
      `create procurement package (${created.procurementMethod}/${created.state})`,
  },
});
