export const dynamic = 'force-dynamic';

import { createByProjectRegisterRoutes } from '@/lib/api/route-factory';
import type { HandoverPacket } from '@/types/handover-packet';
import { createHandoverPacketRequestSchema } from '@/types/handover-packet.schema';

/**
 * GET/POST /api/handover-packets/by-project/[projectId] — SOP 8.1
 * handover packets (PR-26). Creation runs inside one transactional
 * audit (gov't-audit atomicity), matching the hand-written handler.
 *
 * PR-35 — generated by the route factory.
 */
export const { GET, POST } = createByProjectRegisterRoutes<
  HandoverPacket,
  typeof createHandoverPacketRequestSchema._output
>({
  createSchema: createHandoverPacketRequestSchema,
  transactionalCreate: true,
  list: (repos, projectId) => repos.handoverPackets.listByProject(projectId),
  create: (repos, entity) => repos.handoverPackets.create(entity),
  build: (body, { projectId }) => ({
    id: `ho-${crypto.randomUUID()}`,
    projectId,
    contractId: body.contractId ?? null,
    state: 'draft',
    submittedAt: null,
    acceptedAt: null,
    warrantyStartDate: null,
    warrantyEndDate: null,
    acceptedBy: null,
    notes: body.notes?.trim() ?? '',
  }),
  audit: {
    action: 'create_handover_packet',
    resourceType: 'handover_packet',
    decisionReason: (created) =>
      `create handover packet (contractId=${created.contractId ?? 'none'})`,
  },
});
