export const dynamic = 'force-dynamic';

import { createChildRegisterRoutes } from '@/lib/api/route-factory';
import type { OmManualEntry } from '@/types/om-manual';
import { createOmManualEntryRequestSchema } from '@/types/om-manual.schema';

/**
 * GET/POST /api/om-manual-entries/[packetId] — O&M manual catalogue per
 * handover packet (PR-26). Creation runs inside one transactional audit.
 *
 * PR-35 — generated by the route factory.
 */
export const { GET, POST } = createChildRegisterRoutes<
  OmManualEntry,
  typeof createOmManualEntryRequestSchema._output,
  { projectId: string }
>({
  paramName: 'packetId',
  resolveParent: (repos, packetId) => repos.handoverPackets.findById(packetId),
  notFoundMessage: (packetId) => `Handover packet ${packetId} not found`,
  createSchema: createOmManualEntryRequestSchema,
  transactionalCreate: true,
  list: (repos, packetId) => repos.omManualEntries.listByHandoverPacket(packetId),
  create: (repos, entity) => repos.omManualEntries.create(entity),
  build: (body, { parentId }) => ({
    id: `om-${crypto.randomUUID()}`,
    handoverPacketId: parentId,
    category: body.category,
    title: body.title.trim(),
    documentFileId: body.documentFileId ?? null,
    notes: body.notes?.trim() ?? '',
  }),
  audit: {
    action: 'create_om_manual_entry',
    resourceType: 'om_manual_entry',
    decisionReason: (created) =>
      `attach O&M manual entry (${created.category}) "${created.title}"`,
  },
});
