export const dynamic = 'force-dynamic';

import { createByProjectRegisterRoutes } from '@/lib/api/route-factory';
import type { ItSprint } from '@/types/sprint';
import { createItSprintRequestSchema } from '@/types/sprint.schema';

/**
 * GET/POST /api/it-sprints/by-project/[projectId] — Hybrid-Agile
 * sprints (PR-30a). 422 IT_ONLY_FEATURE on non-IT projects.
 * `lifecycleStage` defaults to the project's current stage.
 *
 * PR-35 — generated by the route factory.
 */
export const { GET, POST } = createByProjectRegisterRoutes<
  ItSprint,
  typeof createItSprintRequestSchema._output
>({
  requireIt: true,
  createSchema: createItSprintRequestSchema,
  list: (repos, projectId) => repos.itSprints.listByProject(projectId),
  create: (repos, entity) => repos.itSprints.create(entity),
  build: (body, { projectId, itProject }) => ({
    id: `sp-${crypto.randomUUID()}`,
    projectId,
    lifecycleStage: body.lifecycleStage ?? itProject!.currentLifecycleStage,
    sprintNumber: body.sprintNumber,
    startDate: body.startDate,
    endDate: body.endDate,
    goal: body.goal.trim(),
    velocityPoints: body.velocityPoints,
    completedPoints: body.completedPoints ?? 0,
    notes: body.notes?.trim() ?? '',
  }),
  audit: {
    action: 'create_it_sprint',
    resourceType: 'it_sprint',
    decisionReason: (created) =>
      `create Sprint #${created.sprintNumber} (${created.lifecycleStage})`,
  },
});
