export const dynamic = 'force-dynamic';

import { createByProjectRegisterRoutes } from '@/lib/api/route-factory';
import type { ProjectApprovalRequest } from '@/types/project-approval-request';
import { createProjectApprovalRequestSchema } from '@/types/project-approval-request.schema';

/**
 * PR-27 — Project approval workflow per-project endpoints.
 *
 * GET returns every approval-request row (history + active). POST
 * creates a new submission in state=`submitted`; there is intentionally
 * no constraint preventing multiple in-flight submissions (re-submits
 * after rejection/withdrawal are legitimate). Decisions live on the
 * sibling `/decision` route.
 *
 * PR-35 — generated by the route factory; authz stays
 * `submit_change_request` (the broad "project stakeholder" capability).
 * Note: the factory parses the body BEFORE authz (the canonical
 * pipeline) — the hand-written handler authorized first, so a caller
 * with a malformed body now sees 400 instead of 401/403. Cookieless
 * callers are already 401'd by the middleware (PR-33).
 */
export const { GET, POST } = createByProjectRegisterRoutes<
  ProjectApprovalRequest,
  typeof createProjectApprovalRequestSchema._output
>({
  action: 'submit_change_request',
  createSchema: createProjectApprovalRequestSchema,
  list: (repos, projectId) => repos.projectApprovalRequests.listByProject(projectId),
  create: (repos, entity) => repos.projectApprovalRequests.create(entity),
  build: (body, { projectId, currentUser }) => ({
    id: `par-${crypto.randomUUID()}`,
    projectId,
    submittedBy: currentUser.id,
    submittedAt: new Date().toISOString(),
    state: 'submitted',
    currentApproverRole: 'pm',
    decisionHistory: [],
    notes: body.notes ?? '',
  }),
  audit: {
    action: 'submit_project_approval_request',
    resourceType: 'project_approval_request',
    decisionReason: () => 'submitted for approval',
  },
});
