export const dynamic = 'force-dynamic';

import { createTransitionRoute } from '@/lib/api/route-factory';
import { canTransitionProcurement } from '@/lib/rid/procurement-helpers';
import type { ProcurementPackage } from '@/types/procurement-package';
import { transitionProcurementRequestSchema } from '@/types/procurement-package.schema';

/**
 * POST /api/procurement-packages/[packageId]/transition (PR-24).
 *
 * Body: `{ targetState }` (legacy `{ to }` accepted, PR-31). Illegal
 * edges reject with 422 INVALID_TRANSITION per this surface's original
 * contract.
 *
 * PR-35 — generated by the route factory (PR-34 CAS inside one
 * transactional audit; 409 STATE_CONFLICT when raced).
 */
export const { POST } = createTransitionRoute<
  ProcurementPackage,
  ProcurementPackage['state']
>({
  paramName: 'packageId',
  schema: transitionProcurementRequestSchema,
  load: (repos, id) => repos.procurementPackages.findById(id),
  notFoundMessage: (id) => `Procurement package ${id} not found`,
  projectIdOf: (pkg) => pkg.projectId,
  validate: (pkg, target) => {
    const check = canTransitionProcurement(pkg.state, target);
    if (check.ok) return null;
    return Response.json(
      {
        status: 'error',
        error: { code: 'INVALID_TRANSITION', message: check.reason },
      },
      { status: 422 },
    );
  },
  buildPatch: (_pkg, target) => ({ state: target }),
  cas: (txRepos, pkg, patch) =>
    txRepos.procurementPackages.updateIfState(pkg.id, pkg.state, patch),
  conflictLabel: 'ชุดจัดซื้อ (Procurement package)',
  audit: {
    action: 'transition_procurement_package',
    resourceType: 'procurement_package',
    decisionReason: (pkg, target) => `transition ${pkg.state} -> ${target}`,
  },
});
