export const dynamic = 'force-dynamic';

import { createChildRegisterRoutes } from '@/lib/api/route-factory';
import type { DeliverySlip } from '@/types/delivery-slip';
import { createDeliverySlipRequestSchema } from '@/types/delivery-slip.schema';
import type { WorkPeriod } from '@/types/work-period';

/**
 * GET/POST /api/delivery-slips/[workPeriodId] — ใบส่งมอบงาน per งวดงาน
 * (PR-23, behind FEATURE_RID_PAYMENT_FLOW; 503 BEFORE auth).
 *
 * PR-35 — generated by the route factory.
 */
export const { GET, POST } = createChildRegisterRoutes<
  DeliverySlip,
  typeof createDeliverySlipRequestSchema._output,
  WorkPeriod
>({
  featureFlag: 'FEATURE_RID_PAYMENT_FLOW',
  paramName: 'workPeriodId',
  resolveParent: (repos, workPeriodId) => repos.workPeriods.findById(workPeriodId),
  notFoundMessage: (workPeriodId) => `Work period ${workPeriodId} not found`,
  createSchema: createDeliverySlipRequestSchema,
  list: (repos, workPeriodId) => repos.deliverySlips.listByWorkPeriod(workPeriodId),
  create: (repos, entity) => repos.deliverySlips.create(entity),
  build: (body, { parentId, currentUser }) => ({
    id: `ds-${crypto.randomUUID()}`,
    workPeriodId: parentId,
    submittedAt: new Date().toISOString(),
    submittedBy: currentUser.id,
    attachedDocIds: body.attachedDocIds,
    notes: body.notes?.trim() ?? '',
  }),
  audit: {
    action: 'submit_delivery_slip',
    resourceType: 'delivery_slip',
    decisionReason: (_created, wp) => `delivery slip for งวดที่ ${wp.number}`,
  },
});
