export const dynamic = 'force-dynamic';

import { createChildRegisterRoutes } from '@/lib/api/route-factory';
import { isUniqueViolation } from '@/lib/state-conflict';
import type { ContractAmendment } from '@/types/contract-amendment';
import { createContractAmendmentRequestSchema } from '@/types/contract-amendment.schema';

/**
 * GET/POST /api/contract-amendments/[contractId] — incremental
 * amendments per awarded contract (PR-24).
 *
 * PR-34 — `amendmentNumber` is server-assigned (latest + 1) with one
 * retry on a 23505 race, then 409 SEQUENCE_CONFLICT.
 * PR-35 — generated by the route factory; the sequence loop lives in
 * `performCreate`.
 */
export const { GET, POST } = createChildRegisterRoutes<
  ContractAmendment,
  typeof createContractAmendmentRequestSchema._output,
  { projectId: string }
>({
  paramName: 'contractId',
  resolveParent: (repos, contractId) => repos.awardedContracts.findById(contractId),
  notFoundMessage: (contractId) => `Contract ${contractId} not found`,
  createSchema: createContractAmendmentRequestSchema,
  list: (repos, contractId) => repos.contractAmendments.listByContract(contractId),
  create: (repos, entity) => repos.contractAmendments.create(entity),
  build: () => {
    throw new Error('unused: performCreate owns the amendment create path');
  },
  performCreate: async (repos, body, { parentId }) => {
    let created: ContractAmendment | null = null;
    for (let attempt = 0; attempt < 2 && created === null; attempt += 1) {
      const latest = await repos.contractAmendments.findLatestByContract(parentId);
      const newAmendment: ContractAmendment = {
        id: `am-${crypto.randomUUID()}`,
        contractId: parentId,
        amendmentNumber: (latest?.amendmentNumber ?? 0) + 1,
        amendedAt: body.amendedAt,
        amountDelta: body.amountDelta,
        scheduleDeltaDays: body.scheduleDeltaDays,
        reason: body.reason.trim(),
        approvedBy: body.approvedBy.trim(),
        documentFileId: body.documentFileId ?? null,
      };
      try {
        created = await repos.contractAmendments.create(newAmendment);
      } catch (error) {
        if (!isUniqueViolation(error)) throw error;
      }
    }
    if (created === null) {
      return Response.json(
        {
          status: 'error',
          error: {
            code: 'SEQUENCE_CONFLICT',
            message:
              'มีการบันทึกสัญญาแก้ไขพร้อมกันโดยผู้ใช้อื่น (concurrent amendment) — โปรดลองอีกครั้ง (retry)',
          },
        },
        { status: 409 },
      );
    }
    return created;
  },
  audit: {
    action: 'edit_contract_amendment',
    resourceType: 'contract_amendment',
    decisionReason: (created) =>
      `record amendment #${created.amendmentNumber} (${created.amountDelta} THB, ${created.scheduleDeltaDays} days)`,
  },
});
