export const dynamic = 'force-dynamic';

import { createByProjectRegisterRoutes } from '@/lib/api/route-factory';
import type { WorkPeriod } from '@/types/work-period';
import { createWorkPeriodRequestSchema } from '@/types/work-period.schema';

/**
 * GET/POST /api/work-periods/by-project/[projectId] — งวดงาน register
 * (PR-23, behind FEATURE_RID_PAYMENT_FLOW; 503 BEFORE auth).
 *
 * PR-35 — generated by the route factory; pipeline and envelopes are
 * unchanged from the hand-written handler.
 */
export const { GET, POST } = createByProjectRegisterRoutes<
  WorkPeriod,
  typeof createWorkPeriodRequestSchema._output
>({
  featureFlag: 'FEATURE_RID_PAYMENT_FLOW',
  createSchema: createWorkPeriodRequestSchema,
  list: (repos, projectId) => repos.workPeriods.listByProject(projectId),
  create: (repos, entity) => repos.workPeriods.create(entity),
  build: (body, { projectId }) => {
    const now = new Date().toISOString();
    return {
      id: `wp-${crypto.randomUUID()}`,
      projectId,
      milestoneId: body.milestoneId ?? null,
      number: body.number,
      title: body.title.trim(),
      deliverables: body.deliverables.map((d) => d.trim()).filter(Boolean),
      plannedStartDate: body.plannedStartDate,
      plannedEndDate: body.plannedEndDate,
      amount: body.amount,
      percentage: body.percentage,
      state: body.state ?? 'planned',
      createdAt: now,
      updatedAt: now,
    };
  },
  audit: {
    action: 'create_work_period',
    resourceType: 'work_period',
    decisionReason: (created) => `create งวดที่ ${created.number} (${created.state})`,
  },
});
