export const dynamic = 'force-dynamic';

import { createChildRegisterRoutes } from '@/lib/api/route-factory';
import type { CommitteeInspection } from '@/types/committee-inspection';
import { createCommitteeInspectionRequestSchema } from '@/types/committee-inspection.schema';
import type { WorkPeriod } from '@/types/work-period';

/**
 * GET/POST /api/committee-inspections/[workPeriodId] — การตรวจรับโดย
 * คณะกรรมการ per งวดงาน (PR-23, behind FEATURE_RID_PAYMENT_FLOW).
 * Creation runs inside one transactional audit.
 *
 * PR-35 — generated by the route factory.
 */
export const { GET, POST } = createChildRegisterRoutes<
  CommitteeInspection,
  typeof createCommitteeInspectionRequestSchema._output,
  WorkPeriod
>({
  featureFlag: 'FEATURE_RID_PAYMENT_FLOW',
  paramName: 'workPeriodId',
  resolveParent: (repos, workPeriodId) => repos.workPeriods.findById(workPeriodId),
  notFoundMessage: (workPeriodId) => `Work period ${workPeriodId} not found`,
  createSchema: createCommitteeInspectionRequestSchema,
  transactionalCreate: true,
  list: (repos, workPeriodId) =>
    repos.committeeInspections.listByWorkPeriod(workPeriodId),
  create: (repos, entity) => repos.committeeInspections.create(entity),
  build: (body, { parentId }) => ({
    id: `ci-${crypto.randomUUID()}`,
    workPeriodId: parentId,
    inspectedAt: new Date().toISOString(),
    inspectors: body.inspectors,
    result: body.result,
    conditions: body.conditions?.trim() ?? '',
    documentIds: body.documentIds,
  }),
  audit: {
    action: 'record_committee_inspection',
    resourceType: 'committee_inspection',
    decisionReason: (created, wp) =>
      `committee inspection for งวดที่ ${wp.number}: ${created.result}`,
  },
});
