export const dynamic = 'force-dynamic';

import { createChildRegisterRoutes } from '@/lib/api/route-factory';
import { isUniqueViolation } from '@/lib/state-conflict';
import type { TorDocument } from '@/types/tor-document';
import { createTorDocumentRequestSchema } from '@/types/tor-document.schema';

/**
 * GET/POST /api/tor-documents/[packageId] — TOR revisions per
 * procurement package (PR-24).
 *
 * PR-34 — `version` is server-assigned (latest + 1) with one retry on a
 * 23505 race, then 409 SEQUENCE_CONFLICT.
 * PR-35 — generated by the route factory; the sequence loop lives in
 * `performCreate`.
 */
export const { GET, POST } = createChildRegisterRoutes<
  TorDocument,
  typeof createTorDocumentRequestSchema._output,
  { projectId: string }
>({
  paramName: 'packageId',
  resolveParent: (repos, packageId) => repos.procurementPackages.findById(packageId),
  notFoundMessage: (packageId) => `Procurement package ${packageId} not found`,
  createSchema: createTorDocumentRequestSchema,
  list: (repos, packageId) => repos.torDocuments.listByProcurementPackage(packageId),
  create: (repos, entity) => repos.torDocuments.create(entity),
  build: () => {
    throw new Error('unused: performCreate owns the TOR create path');
  },
  performCreate: async (repos, body, { parentId }) => {
    let created: TorDocument | null = null;
    for (let attempt = 0; attempt < 2 && created === null; attempt += 1) {
      const latest = await repos.torDocuments.findLatestByProcurementPackage(parentId);
      const newTor: TorDocument = {
        id: `tor-${crypto.randomUUID()}`,
        procurementPackageId: parentId,
        version: (latest?.version ?? 0) + 1,
        scopeSummary: body.scopeSummary.trim(),
        technicalRequirements: body.technicalRequirements.trim(),
        deliverySchedule: body.deliverySchedule.trim(),
        evaluationCriteria: body.evaluationCriteria.trim(),
        documentFileId: body.documentFileId ?? null,
        approvedAt: body.approvedAt ?? null,
      };
      try {
        created = await repos.torDocuments.create(newTor);
      } catch (error) {
        if (!isUniqueViolation(error)) throw error;
      }
    }
    if (created === null) {
      return Response.json(
        {
          status: 'error',
          error: {
            code: 'SEQUENCE_CONFLICT',
            message:
              'มีการยื่น TOR ฉบับใหม่พร้อมกันโดยผู้ใช้อื่น (concurrent TOR filing) — โปรดลองอีกครั้ง (retry)',
          },
        },
        { status: 409 },
      );
    }
    return created;
  },
  audit: {
    action: 'edit_tor_document',
    resourceType: 'tor_document',
    decisionReason: (created) => `file TOR v${created.version}`,
  },
});
