export const dynamic = 'force-dynamic';

import { createChildRegisterRoutes } from '@/lib/api/route-factory';
import type { AssetRegistration } from '@/types/asset-registration';
import { createAssetRegistrationRequestSchema } from '@/types/asset-registration.schema';

/**
 * GET/POST /api/asset-registrations/[packetId] — RID asset-system-
 * compatible asset register per handover packet (PR-26).
 *
 * PR-35 — generated by the route factory.
 */
export const { GET, POST } = createChildRegisterRoutes<
  AssetRegistration,
  typeof createAssetRegistrationRequestSchema._output,
  { projectId: string }
>({
  paramName: 'packetId',
  resolveParent: (repos, packetId) => repos.handoverPackets.findById(packetId),
  notFoundMessage: (packetId) => `Handover packet ${packetId} not found`,
  createSchema: createAssetRegistrationRequestSchema,
  list: (repos, packetId) =>
    repos.assetRegistrations.listByHandoverPacket(packetId),
  create: (repos, entity) => repos.assetRegistrations.create(entity),
  build: (body, { parentId }) => ({
    id: `ar-${crypto.randomUUID()}`,
    handoverPacketId: parentId,
    assetCode: body.assetCode.trim(),
    assetType: body.assetType,
    installedAt: body.installedAt,
    installedLocation: body.installedLocation.trim(),
    initialValue: body.initialValue,
    costCenter: body.costCenter ?? null,
    notes: body.notes?.trim() ?? '',
  }),
  audit: {
    action: 'create_asset_registration',
    resourceType: 'asset_registration',
    decisionReason: (created) =>
      `register asset ${created.assetCode} (${created.assetType}) @ ${created.installedLocation}`,
  },
});
