export const dynamic = 'force-dynamic';

import { createTransitionRoute } from '@/lib/api/route-factory';
import { canTransitionSow } from '@/lib/rid/it-class-helpers';
import type { VendorSow } from '@/types/vendor-sow';
import { transitionVendorSowRequestSchema } from '@/types/vendor-sow.schema';

/**
 * POST /api/vendor-sows/[sowId]/transition — advance a SOW through
 * `draft → agreed → in_delivery → uat → accepted | rejected` (PR-30a).
 * 409 STATE_TRANSITION_REJECTED on illegal edges; signedAt stamps at
 * `agreed`, acceptedAt at `accepted`.
 *
 * PR-35 — generated by the route factory (PR-34 CAS inside one
 * transactional audit; 409 STATE_CONFLICT when raced).
 */
export const { POST } = createTransitionRoute<VendorSow, VendorSow['state']>({
  requireIt: true,
  paramName: 'sowId',
  schema: transitionVendorSowRequestSchema,
  load: (repos, id) => repos.vendorSows.findById(id),
  notFoundMessage: (id) => `Vendor SOW ${id} not found`,
  projectIdOf: (sow) => sow.projectId,
  validate: (sow, target) => {
    const decision = canTransitionSow(sow.state, target);
    if (decision.ok) return null;
    return Response.json(
      {
        status: 'error',
        error: {
          code: 'STATE_TRANSITION_REJECTED',
          message: `Transition "${sow.state}" → "${target}" is not allowed.`,
          reason: decision.reason,
        },
      },
      { status: 409 },
    );
  },
  buildPatch: (sow, target) => {
    const now = new Date().toISOString();
    const patch: Partial<VendorSow> = { state: target };
    if (target === 'agreed' && sow.signedAt === null) patch.signedAt = now;
    if (target === 'accepted' && sow.acceptedAt === null) patch.acceptedAt = now;
    return patch;
  },
  cas: (txRepos, sow, patch) => txRepos.vendorSows.updateIfState(sow.id, sow.state, patch),
  conflictLabel: 'SOW (Vendor SOW)',
  audit: {
    action: 'transition_vendor_sow',
    resourceType: 'vendor_sow',
    decisionReason: (sow, target) => `SOW "${sow.phase}": ${sow.state} → ${target}`,
    beforeOf: (sow) => ({
      state: sow.state,
      signedAt: sow.signedAt,
      acceptedAt: sow.acceptedAt,
    }),
    afterOf: (updated) => ({
      state: updated.state,
      signedAt: updated.signedAt,
      acceptedAt: updated.acceptedAt,
    }),
  },
});
